linters-settings:
  lll: 
    line-length: 128
    tab-width: 2
    autofix: true
linters:
  enable:
    - lll
    - errcheck
    - gosimple 
    - govet 
    - ineffassign
    - staticcheck 
    - structcheck
    - typecheck
    - unused 
    - varcheck
    # - cyclop
    # - funlen
    # - gocritic
    # - gocyclo
    # - gofmt