linters-settings:
  lll: 
    line-length: 128
    tab-width: 2
    autofix: true
  funlen:
   ignore-comments: true
linters:
  enable:
    - lll
    - errcheck
    - gosimple 
    - govet 
    - ineffassign
    - staticcheck 
    - typecheck
    - unused 
    - funlen
    - cyclop
    - goconst
    - gofmt
    - godox
    - misspell
    - reassign
    - whitespace