name: Keploy

on:
  pull_request:

jobs:
  go_linux_app:
    runs-on: ubuntu-latest
    environment: secrets  # Ensure you specify the environment if it's an environment-level secret
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        mkdir -p $HOME/.docker/cli-plugins
        curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-x86_64" -o $HOME/.docker/cli-plugins/docker-compose
        chmod +x $HOME/.docker/cli-plugins/docker-compose
        echo "$HOME/.docker/cli-plugins" >> $GITHUB_PATH
        docker-compose --version

    - name: Install python
      uses: actions/setup-go@v2
      with:
          go-version: "1.22"

    - name: Run the go template
      run: |
        chmod +x ${GITHUB_WORKSPACE}/.github/workflows/test_workflows/app.sh
        ${GITHUB_WORKSPACE}/.github/workflows/test_workflows/app.sh
      env:
        GITHUB_TOKEN: ${{ secrets.SECRETS }}

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     files: ./coverage/lcov.info
    #     verbose: true