name: Keploy

on:
  pull_request:

jobs:
  python_linux:
    runs-on: ubuntu-latest
    environment: secrets  # Ensure you specify the environment if it's an environment-level secret
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: "1.22"
      - name: Run the go template
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/workflows/test_workflows/keploy.sh
          ${GITHUB_WORKSPACE}/.github/workflows/test_workflows/keploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.SECRETS }}

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     files: ./coverage/lcov.info
    #     verbose: true