// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Comments", testCommentsUpsert)

	t.Run("Companies", testCompaniesUpsert)

	t.Run("Followers", testFollowersUpsert)

	t.Run("Locations", testLocationsUpsert)

	t.Run("Posts", testPostsUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("Users", testUsersUpsert)
}
